version: "3.9"

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: mysql+aiomysql://root:1234@db:3306/diffusiondb
      APP_NAME: Forward Diffusion API
      ENV: docker
      FRONTEND_ORIGIN: http://localhost:5173
      JWT_SECRET: fasfhaskfhkas!kjfkdsanfdfasfasf
      JWT_ALG: HS256
      ACCESS_TOKEN_TTL_MIN: 100
      REFRESH_TOKEN_TTL_DAYS: 7
      COOKIE_DOMAIN: localhost
      SECURE_COOKIES: False


  frontend:
    build: ./frontend
    environment:
      - VITE_API_URL=http://backend:8000
    container_name: react_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app     
      - /app/node_modules    
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: diffusiondb
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234"]
      interval: 10s
      retries: 5
      start_period: 20s


volumes:
  db_data:
